#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_follows_pointer true

bspc rule -a Pavucontrol state=floating
bspc rule -a feh state=floating
bspc rule -a Gimp state=floating
bspc rule -a Lxappearance state=floating
bspc rule -a *:my_float state=floating

~/.fehbg &
picom &
polylaunch.sh &

# source the colors.
. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color4"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "$color1"
sxhkd -c /home/paddy/.config/sxhkdrc/sxhkdrc &
